jackal_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

jackal_velocity_controller:
  # type: "diff_drive_controller/DiffDriveController"
  type: "jackal_diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2

ekf_localization:
  frequency: 50
  odom0: /jackal_velocity_controller/odom
  odom0_config: [true, true, false,
                 false, false, false,
                 true, true, true,
                 false, false, true]
  odom0_differential: true
  imu0: /imu/data
  imu0_config: [false, false, false,
                true, true, true,
                false, false, false,
                true, true, true]
  imu0_differential: false
  odom_frame: odom
  base_link_frame: base_link
