map_type: costmap 
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 10.0
raytrace_range: 10.5

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.1

plugins:
- {name: footprint_layer, type: "costmap_2d::FootprintLayer"}
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: front_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 10.0, raytrace_range: 10.0}

inflater_layer:
 inflation_radius: 0.5
